server:
  port: 9991
  
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1/XE
    username: products
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    database: oracle
    show-sql: true
    
  application:
    name: products_service #// 应用程序名，可显示为提供的服务名。
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7771/eureka/
  instance:
    prefer-ip-address: true   # 用ip地址注册。
    